### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pablododda** [eddiesigner/sketch-map-generator#14]
It stopped working for me, I think it was after a Sketch update.

**Comment by mccchip** [comment]
I have had the same experience. I was using Mapagenerator today with Sketch 46.2, I was able to fill  3-4 rectangles with various maps, then it just stopped filling any rectangles. The Plugins menu would highlight as if it was understanding the shortcut key to generate a map but nothing filled the rectangle.  I restarted the app, restarted the machine and even uninstalled and reinstalled the plug in. None of that worked.

Any thoughts????

**Comment by eddiesigner** [comment]
I just released the version 2.0 (it's a version builded from scratch).

Please uninstall the version you have and install the new version: https://github.com/eddiesigner/sketch-map-generator#manual

The plugin now supports Google Maps and Mapbox 😄

**Comment by mccchip** [comment]
Thanks Eduardo,

It is working for me. 
Love the plugin and the new features.

Chip McCarthy

Freelance Creative Director
www.chipmccarthy.com
