### ISSUE TITLE
Mapbox maps not working - Sketch 46.2

### ISSUE THREAD

**Issue by christianhals** [eddiesigner/sketch-map-generator#16]
I just found this great plugin today, and Google Maps is working fine.

When I tryto use Mapbox I just get an error message:

> There was a poblem, please check the adress settings.

I´ve been trying to enter exactly the adress used in the readme "Jagerstraße 16 Linz".

I installed the plugin via Sketchpacks.

**Comment by joshsanders** [comment]
same... this has been happening for me since yesterday. 

installed via sketchpacks, running sketch 46.2 on macOS Sierra 10.12.6

this is a huge issue since my product team uses mapbox for maps in production, and handing off mockups that reference only the working google maps visuals is not ideal.

Love this plugin tho! hopefully this gets fixed ASAP

**Comment by eddiesigner** [comment]
@christianhals That's weird, I tried with the same address (Jagerstraße 16 Linz) and it's working fine. Have you tried with "Jagerstrasse 16 Linz"?

@joshsanders You have the same problem with the same address or what address are you trying to use?

Btw, it would be great if both of you can follow these steps to debugging the plugin: https://github.com/eddiesigner/sketch-map-generator/wiki/Debugging-Sketch-Map-Generator 

Please let me know your results!

**Comment by christianhals** [comment]
Thanks for your feedback @eddiesigner and @joshsanders 

I just started using the plugin today, and it was not working for several hours for Mapbox. Typing in the same adresses now I can see that it is working fine. Maybe it could have been a temporary Mapbox problem that is now resolved?

As @joshsanders reported seems the problem has been present for some time.

Oh, and thanks for a very nice plugin that will definitely save me some time.

**Comment by joshsanders** [comment]
@eddiesigner   i was having issues with any address i tried... tried quite a few actually ha.  Anywhoo... oddly it seems like it's working now. Not sure what was causing the issue ... perhaps it was indeed something on mapbox's end. Thanks for the debugging link, somehow I hadn't seen that previously when i was looking for solutions. 

Glad it's working now!  Thanks again for the dope plugin! 👍

**Comment by eddiesigner** [comment]
Thank you @christianhals and @joshsanders for the comments, I think it was caused because the Mapbox API requests/minute were reached due the plugin was kind of popular at the beginning but now everything is more stable 😄
