### ISSUE TITLE
Check the address settings

### ISSUE THREAD

**Issue by Felixchip** [eddiesigner/sketch-map-generator#20]
When I try generating a map using the Mapbox option, 
it pops up an error message that reads "There was a problem, please check the address settings".

That of Google Maps works just fine.
I only happen to prefer the Mapbox.

I'll appreciate if there's a way around this.

**Comment by eddiesigner** [comment]
Which address are you trying to use?

**Comment by lyapustin** [comment]
Same here. But even worse — I can't generate google map: “The style cannot be applied” (there's no Snazzy Maps' code in the box). And layer became filled with fully transparent fill.
Sometimes it tells nothing, leaving me with the same transparent-filled layer.
Changing the location (Barcelona, New York, Paris) doesn't change the result.

Sketch 46.1, macOS Sierra 10.12.6

**Comment by eddiesigner** [comment]
Please update Sketch to the version 47 and please also update the plugin version, the latest version is the 2.0.2

**Comment by AlbertReinhardt** [comment]
I'm using Sketch 47 and plugin 2.0.2. I also get the error  "There was a problem, please check the address settings" when generating with mapbox. This is true for any zoom level, map type, and address tried - specifically 
1301 64th St, Emeryville, CA 94608
or Emeryville, CA

**Comment by eddiesigner** [comment]
I tried with both addresses and for me it's working as expected. The thing is sometimes Mapbox doesn't return a map because the API rate limit is reached (I'm using the free version of that), so please try again or maybe later and it will work.
