### ISSUE TITLE
Option to align/offset map

### ISSUE THREAD

**Issue by kudigaracoder** [eddiesigner/sketch-map-generator#21]
Hi,
Would it be possible to introduce an align/offset option wherein I could could specify by how much the location I search for should be offset from the centre?
I'm overlaying text on the map layer; the generated map is centred & inserted as image fill on the map layer; I'd like to show the Text on the left while offsetting the map to the right.

**Comment by eddiesigner** [comment]
Hi, sorry for the late.

I think that feature is too specific, my goal is to keep the plugin as simple and easy to use as posible, I don't want to add options to the UI that might are not so common for most of the users. In your case you can generate the map and play with your layers to get the desired result :)

Cheers!
