### ISSUE TITLE
style cannot be applied

### ISSUE THREAD

**Issue by rmedjek** [eddiesigner/sketch-map-generator#22]
i am running sketch 41.2, and whenever i run the plugin it says style cannot be applied??
any thoughts?

**Comment by eddiesigner** [comment]
Hi, sorry for the late.

The thing is Sketch changed some internal methods and I had to update the plugin accordingly, you can see it more in detail here: https://github.com/eddiesigner/sketch-map-generator/issues/18#issuecomment-335627259

May you update Sketch to the latest version? 😅  

Cheers!
