### ISSUE TITLE
Gmap screenshot too big

### ISSUE THREAD

**Issue by hey-duda** [eddiesigner/sketch-map-generator#25]
Google Map Screenshots are generated too big. Strangely it's always exactly 3% extra height.

EDIT:
It's actually pretty random, but in a squarish format.

**Comment by eddiesigner** [comment]
You have an example? Or it's something about the labels size?

See here: https://github.com/eddiesigner/sketch-map-generator/issues/5

**Comment by mikaelce** [comment]
I also have this problem. Doesn't help to change zoom level. It also looks pixelated.

**Comment by hey-duda** [comment]
It seems that the fill gets generated too big, if you exceed a certain size.

![sketch-map-generator-bug](https://user-images.githubusercontent.com/36629548/38609084-748aaf5c-3d7d-11e8-9f9c-bba533b6f57f.png)

**Comment by eddiesigner** [comment]
The thing is the Google Maps Static API doesn't allow sizes greater than 640 x 640 pixels: https://developers.google.com/maps/documentation/maps-static/usage-and-billing#image-sizes

I mean, it is possible but then I would have to pay 😐
