### ISSUE TITLE
Problem generating Mapbox map greater than 1280 pixels wide

### ISSUE THREAD

**Issue by nonoumasy** [eddiesigner/sketch-map-generator#26]
![screen shot 2018-02-23 at 8 57 01 pm](https://user-images.githubusercontent.com/6312676/36625842-308c7fb2-18dc-11e8-8c7d-102543dfa87a.png)

There might also be a height limit

**Comment by eddiesigner** [comment]
You're right, according to the Mapbox documentation there is a limit of 1280px for both height and width :/

As a workaround you can generate it using a smaller size and then scale it using Sketch.
