### ISSUE TITLE
Street names too big

### ISSUE THREAD

**Issue by javierlosada** [eddiesigner/sketch-map-generator#28]
Hi,

First of all, congratulations for this great plugin.

I've noticed that now the streets and neighborhoods labels are much bigger than usual. Not sure if since the last Sketch or plugin update.

![map](https://user-images.githubusercontent.com/18560469/40119573-53d2e9bc-591d-11e8-8f26-b9619c8af165.png)

Best
J

**Comment by eddiesigner** [comment]
Unfortunely the Google Maps Static API doesn't allow to change the font size or something like that to the road labels:
https://developers.google.com/maps/documentation/maps-static/styling#style-rules

So there's not much I can do about it :/
