### ISSUE TITLE
Retina support

### ISSUE THREAD

**Issue by OllieBrkr** [eddiesigner/sketch-map-generator#29]
First off love the plugin! Incredibly useful.

One thing that would be great though is retina support. When designing @2x there's no way to stop the maps looking blurry, so I have to resort to screenshoting Google Maps on my retina display.

**Comment by eddiesigner** [comment]
The thing is the Google Maps Static API doesn't allow sizes greater than 640 x 640 pixels (1280 x 1280 @2x):
https://developers.google.com/maps/documentation/maps-static/usage-and-billing#image-sizes

I mean, it is possible but then I would have to pay 😐
