### ISSUE TITLE
Suggestion: integrate with Snazzy maps

### ISSUE THREAD

**Issue by renatodeleao** [eddiesigner/sketch-map-generator#3]
First of all thanks for this plugin, works awesome and it saves a lot of *screenshooting*!

This is just a suggestion, how about integrate this with snazzy maps themes (https://snazzymaps.com/) to allow style customisation of map? 

For what I can see you're getting a static image  from google maps API. From the documentation you can pass a style object to the url for styling. You can get that object from snazzy maps api. 💥 

Probably isn't so linear as I think, but is a starting point. 
This would be great to get maps with the look & feel of your app, taking of labels and other designer stuff...

Once again, many thanks! Keep shipping!

**Comment by eddiesigner** [comment]
It's a fantastic idea and is now integrated! :) Thank you for use the plugin @renatodeleao

**Comment by renatodeleao** [comment]
Awwww yeeahh! 🙌  :shipit:
