### ISSUE TITLE
Add support for sketch-data-populator and dynamic maps

### ISSUE THREAD

**Issue by treshenry** [eddiesigner/sketch-map-generator#30]
Adding a command that looks for the location data from the layer's metadata (instead of a dialog) would enable dynamically generating maps from real data.

https://github.com/preciousforever/sketch-data-populator/issues/128

**Comment by eddiesigner** [comment]
I think I can do that, the only thing I need is a dummy Sketch file where I can get the metadata from a layer generated by Data Populator because I don't know what kind of data I'll get at the moment.

**Comment by eddiesigner** [comment]
I will close this issue since there has not been any recent activity, please feel free to reopen it if you consider it necessary.
