### ISSUE TITLE
Mapbox doesn’t seem to work any more.

### ISSUE THREAD

**Issue by PDXIII** [eddiesigner/sketch-map-generator#33]
Sorry, but can’t provide any other information. Google works as expected. Choosing Mapbox doesn’t show any result.

**Comment by leeharding** [comment]
Came here to say the same thing. Google works fine, choosing Mapbox, looks like it's going to work, but doesn't apply anything at all. thanks.

**Comment by eddiesigner** [comment]
Sorry guys, there was an issue with the geocoding API but now it works, please update the plugin to the latest version (2.0.4).
