### ISSUE TITLE
Sketch 52 Incompatibility

### ISSUE THREAD

**Issue by CharlieMouton** [eddiesigner/sketch-map-generator#34]
After updating to Sketch 52, uses google or mapbox yields the error "Shape layer only: Your selection was a “Rectangle”, that is not a shape layer. Please select a shape layer." This error occurs even when I have a basic rectangle selected. I'm guessing they changed something in how layers are identified that interferes with the layer validation that this plugin uses. 

Would really appreciate having this fixed. My team and I love this plugin!

**Comment by maxart2007** [comment]
After editing common.js (line 26) and replacing if statement
`if ([layer class] != MSShapeGroup) {`
with
`if (([layer class] != MSRectangleShape)) {`
everything just worked.

Sorry, don't have time to make a pull request at the moment :)

**Comment by eddiesigner** [comment]
@CharlieMouton Thanks for the heads up! Now it works just fine 👍 

You was right, they made some internal changes related to the shapes but now the plugin supports both kind of approaches.

Please update the plugin to the latest version (2.0.4).

**Comment by eddiesigner** [comment]
@maxart2007 That would work just for rectangles but not for other kind of shapes like circles, triangles and so on.

The best way to do it is checking for a common property shared by all this kind of instances. All of them use the `MSShapePathLayer` protocol so now I check for the `edited` property which is shared by all of them.

**Comment by maxart2007** [comment]
Yes, I realize. Thanks for the quick update!
