### ISSUE TITLE
Mapbox generator not working with Sketch 52.2

### ISSUE THREAD

**Issue by laurencolson** [eddiesigner/sketch-map-generator#36]
Nothing happens when I try to generate a map using Mapbox (Google Maps works fine).

**Comment by eddiesigner** [comment]
Do you have the latest version of the plugin (2.0.4)? Which address are you trying to put? I've just tried and it works fine with Sketch 52.2

**Comment by eddiesigner** [comment]
Ok, there was an encoding issue but now I've fixed it, please update the plugin :)
