### ISSUE TITLE
Styles not rendering correctly

### ISSUE THREAD

**Issue by aalokt89** [eddiesigner/sketch-map-generator#4]
I have a problem where pasted styles from Snazzy Maps are not rendering correctly. Not sure if I'm doing it right but objects and styles are definitely not displaying right. 

Snazzy Maps style 1: https://screencast.com/t/PKQluCjLv
Plugin generated map 1: https://screencast.com/t/yHG9zcNMfb8

Vid: https://screencast.com/t/yoJZjdVF

**Comment by eddiesigner** [comment]
The only problem with that theme is the color text. In the first object style you can see a line which says: `"saturation": 36`, that's the problem, if you remove that line the theme works fine.

You can try with this code:

```
[ { "featureType": "all", "elementType": "labels.text.fill", "stylers": [ { "color": "#000000" }, { "lightness": 40 } ] }, { "featureType": "all", "elementType": "labels.text.stroke", "stylers": [ { "visibility": "on" }, { "color": "#000000" }, { "lightness": 16 } ] }, { "featureType": "all", "elementType": "labels.icon", "stylers": [ { "visibility": "off" } ] }, { "featureType": "administrative", "elementType": "geometry.fill", "stylers": [ { "color": "#000000" }, { "lightness": 20 } ] }, { "featureType": "administrative", "elementType": "geometry.stroke", "stylers": [ { "color": "#000000" }, { "lightness": 17 }, { "weight": 1.2 } ] }, { "featureType": "landscape", "elementType": "geometry", "stylers": [ { "color": "#000000" }, { "lightness": 20 } ] }, { "featureType": "poi", "elementType": "geometry", "stylers": [ { "color": "#000000" }, { "lightness": 21 } ] }, { "featureType": "road.highway", "elementType": "geometry.fill", "stylers": [ { "color": "#000000" }, { "lightness": 17 } ] }, { "featureType": "road.highway", "elementType": "geometry.stroke", "stylers": [ { "color": "#000000" }, { "lightness": 29 }, { "weight": 0.2 } ] }, { "featureType": "road.arterial", "elementType": "geometry", "stylers": [ { "color": "#000000" }, { "lightness": 18 } ] }, { "featureType": "road.local", "elementType": "geometry", "stylers": [ { "color": "#000000" }, { "lightness": 16 } ] }, { "featureType": "transit", "elementType": "geometry", "stylers": [ { "color": "#000000" }, { "lightness": 19 } ] }, { "featureType": "water", "elementType": "geometry", "stylers": [ { "color": "#000000" }, { "lightness": 17 } ] } ]
```

**Comment by aalokt89** [comment]
But this happens for every style I try to copy and paste. No matter which one I copy, The styles are not entirely correct, and I don't know which ones are and aren't

**Comment by aalokt89** [comment]
It's doing this for every style, though. No matter which one I copy, there are styles that are correct and styles that are incorrect.

**Comment by aalokt89** [comment]
Ahh ok, I think the styles Snazzy Maps is generating are incorrect. It would be super helpful if the styles field was much bigger, so editing is much easier https://screencast.com/t/K6SZZDwaW3Q

**Comment by eddiesigner** [comment]
The input field is bigger now:

![Snazzy Maps Input Field](https://d2ppvlu71ri8gs.cloudfront.net/items/2X1e2k3m0y022U1V2p0J/Image%202017-04-16%20at%204.04.08%20PM.png)

👍
