### ISSUE TITLE
Store data within the layer

### ISSUE THREAD

**Issue by lanceplaine** [eddiesigner/sketch-map-generator#40]
Hi,

When generating a map it would be great if the address and zoom level could be store and reused automatically using maybe the layer name.

Currently I do it manually but it would be great if it can be automatic.

Thanks!

<img width="1552" alt="screen shot 2018-11-21 at 8 35 18 am" src="https://user-images.githubusercontent.com/5476205/48855235-87787400-ed68-11e8-879a-ea7da1523a01.png">

<img width="1552" alt="screen shot 2018-11-21 at 8 38 34 am" src="https://user-images.githubusercontent.com/5476205/48855426-e211d000-ed68-11e8-9795-48956ea0f8e9.png">

**Comment by eddiesigner** [comment]
Hi, this is finally implemented in the latest version (3.1.2).

Cheers.

**Comment by lanceplaine** [comment]
Awesome, thanks!
