### ISSUE TITLE
Plugin does not work sketch 50.2 plugin 3.0

### ISSUE THREAD

**Issue by bot9987** [eddiesigner/sketch-map-generator#41]
Hi,
The plugin does nothing when trying to use it.
Nothing is written on console.
Sketch 50.2
Plugin 3.0

**Comment by bot9987** [comment]
2.0.6 works

**Comment by hyeashish** [comment]
I added this plugin recently and when I run it, no map is generated. I have sketch 52.5. Plugin 3.0

**Comment by eddiesigner** [comment]
@bot9987 What address are you trying to use?

Also please read [this post](https://github.com/eddiesigner/sketch-map-generator/wiki/Debugging-Sketch-Map-Generator) to debug the plugin so I can know more about the issue since I don't have that Sketch version.

**Comment by eddiesigner** [comment]
@hyeashish What address are you trying to use? Can you see the live preview?

Also please read [this post](https://github.com/eddiesigner/sketch-map-generator/wiki/Debugging-Sketch-Map-Generator) to debug the plugin so I can know more about the issue since I don't have that Sketch version.

**Comment by tmyknze** [comment]
The preview works just fine, but when I generate nothing happens and I get a notification that I should check the address settings. I've used state names, specific addresses, and moved the preview pin to generate an address and nothing seems to work. I have Sketch 53.2

**Comment by eddiesigner** [comment]
@tmyknze are you using Google Maps or Mapbox? I just tested it using Sketch 53.2 and it works with both and using different addresses 🤔

Also, can you tell me what address are you trying to use?

**Comment by aimanfakia** [comment]
It is not working with the latest version nothing is generated

**Comment by eddiesigner** [comment]
@aimanfakia do you mean the latest version of the plugin or Sketch?

With the latest version of the plugin you have to use your own API keys as described here:

https://github.com/eddiesigner/sketch-map-generator/wiki/How-to-generate-a-Google-Maps-key
https://github.com/eddiesigner/sketch-map-generator/wiki/How-to-get-your-Mapbox-tokens

I have the latest version of Sketch and the plugin works just fine.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if you think is necessary.
