### ISSUE TITLE
Shape Layer Must Be Vertical

### ISSUE THREAD

**Issue by jmertz** [eddiesigner/sketch-map-generator#45]
Very helpful plugin, thank you! For certain aspect ratios of shape layers however, the plugin seems to generate the following error: "There was a problem. Please check the address settings." The fix appears to be to use a different size of shape layer, and then rescale the shape after the map has been generated.

**Comment by eddiesigner** [comment]
Hi! I wasn't able to reproduce it :/ 

Can you tell me please what aspect ratio you was using? or maybe the size of the layer.

Also, were you using Google Maps or Mapbox? That message should indicates another kind of error.

**Comment by sahilk** [comment]
Facing the same issue with Mapbox. Layer size is 2160*756. Works fine with Gmaps.

**Comment by eddiesigner** [comment]
Sorry fo the late response but I was on vacation. Sadly this is a restriction of Mapbox, the max size you can use is 1280 pixels (https://docs.mapbox.com/api/maps/#retrieve-a-static-map-from-a-style).

In the latest version I changed the way to display the error and now you can see a more descriptive message.

As a *workaround* you can set the width to 1280 and then manually make the layer bigger. I know is not perfect but could be a *solution*.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if you think is necessary.
