### ISSUE TITLE
Dynamic or half-decimal zoom levels

### ISSUE THREAD

**Issue by giap** [eddiesigner/sketch-map-generator#48]
Would it be possible to allow zoom level to be input at a zoom level of choice also when it comes to the first two decimals or at least to have half-decimal zoom levels (e.g.: 1.5,2.5,etc)?

**Comment by eddiesigner** [comment]
With the latest version (3.5.1) this feature is supported but it's not a text field because then you could write anything you want (even letters) and the validation for that is beyond the scope of this plugin.

**Comment by giap** [comment]
Thanks so much @eddiesigner , so nice of you!
I only have the problem that now it is not working for me. Whenever I run the Mapbox map generator I get a notification that tells me "please ave your Mapbox toke first". I created another token and restarted and it still gives me that message as response. Am I missing something?

**Comment by giap** [comment]
Found it! I needed to add the public token as well, thanks a lot again!
