### ISSUE TITLE
Cannot Preview Map in Sketch 59.1

### ISSUE THREAD

**Issue by andrewtsuei** [eddiesigner/sketch-map-generator#49]
The preview area is blank even Google Maps API Key is saved.
Generate function is OK.

**Comment by eddiesigner** [comment]
Did you follow these instructions to generate your API key? https://github.com/eddiesigner/sketch-map-generator/wiki/How-to-generate-a-Google-Maps-key

Please make sure your API key has enabled the **Maps** and **Places** products, as you can see in step 2.

**Comment by phillito** [comment]
@eddiesigner In reference to the #47 we are having the same issue using our Enterprise key. Generating a key, on a separate personal account, we don't have any issues with the preview feature. Would you know why an Enterprise account might be different?

**Comment by eddiesigner** [comment]
@phillito could be that your Enterprise key has some kind of restriction? Please refer to: https://cloud.google.com/docs/authentication/api-keys?rd=1&visit_id=637095036986453679-3732838093

Maybe the Geocoding API or the Maps Javascript API are disabled.

**Comment by phillito** [comment]
@eddiesigner All fixed. We were generating the key from our Enterprise API dashboard, so assume those options were not enabled as you suggested. Creating the key through the standard Google Maps account site using our Enterprise credentials fixed it.

**Comment by eddiesigner** [comment]
Glad to hear you solved it :)
