### ISSUE TITLE
Can't generate map & preview it

### ISSUE THREAD

**Issue by DashingNass** [eddiesigner/sketch-map-generator#50]
Hi, my colleague introduced me to this awesome plugin.
But unfortunately **_I can't generate and can't see the preview modus._**
I use Sketch version 60.1

Thanks in advance for your help :)

**Comment by eddiesigner** [comment]
Are you using Google Maps or Mapbox?

**Comment by DashingNass** [comment]
I use Google Maps

**Comment by eddiesigner** [comment]
Did you follow [these steps](https://github.com/eddiesigner/sketch-map-generator/wiki/How-to-generate-a-Google-Maps-key) to generate your API Key?

Pay special attention to step number 2.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if you think is necessary.
