### ISSUE TITLE
feature proposal: re-create previous map

### ISSUE THREAD

**Issue by ralts00** [eddiesigner/sketch-map-generator#51]
Hi
Thanks for this plugin, I adore it.
I hope you can create a shortcut to re-create a map with the same options as the last map generated.

**Comment by eddiesigner** [comment]
Nice idea, I will try to implement that soon

**Comment by eddiesigner** [comment]
I already implemented this feature, please download the latest version if you want to give it a try 🙂 

https://github.com/eddiesigner/sketch-map-generator/releases/tag/v3.5.3

**Comment by ralts00** [comment]
Thanks :D :D
