### ISSUE TITLE
Preview works, but shape stays empty

### ISSUE THREAD

**Issue by sli131** [eddiesigner/sketch-map-generator#52]
Hi – 

Plugin interface works perfect with preview, but hitting Generate has no effect, the selected shape remains empty (but the layer name is updated to the address)

Followed steps to copy entries in Console.app
Text file attached
[console.txt](https://github.com/eddiesigner/sketch-map-generator/files/4102560/console.txt)

Sketch v58
Map Generator 3.5.4
OS X 10.15.2

**Comment by sli131** [comment]
Oh, there is a small error message that appears in a popup in sketch:
_There was a problem, please check your internet connection or address settings_

**Comment by eddiesigner** [comment]
This is happening with Google Maps, Mapbox or both? It happens with any address or just with one in specific?

**Comment by sli131** [comment]
It happens with any address for Google Maps only, Mapbox works fine.

**Comment by eddiesigner** [comment]
Did you follow these steps to generate your Google Maps API Key? https://github.com/eddiesigner/sketch-map-generator/wiki/How-to-generate-a-Google-Maps-key

Step number two is super important.

Also, you should check if your API Key has some restrictions: https://cloud.google.com/docs/authentication/api-keys#api_key_restrictions

**Comment by sli131** [comment]
I have a laptop running the same configuration, except that the OS is 10.14.3 (Mojave) – there everything works as expected...

**Comment by eddiesigner** [comment]
The OS is not the problem, I also have both (Mojave and Catalina) and it works well. Can you please follow [these steps](https://github.com/eddiesigner/sketch-map-generator/wiki/Debugging-Sketch-Map-Generator) but this time make sure of clearing the console before you press the [Generate] button and then copy the whole output?

What about Sketch? Do you have the same version in both laptops?

**Comment by sli131** [comment]
Yes, sketch versions are both v58
Here's another console output, cleared just before using the plug
[console2.txt](https://github.com/eddiesigner/sketch-map-generator/files/4117394/console2.txt)

ps for some reason there is also no more map in the preview window now (on the problem machine with Catalina that is, Mojave version everything still fine)

Appreciate the help, thank you

**Comment by eddiesigner** [comment]
I saw in the logs that some network error happened, I'm not entirely sure if it was caused by the plugin though.

Please download the plugin from the following link and follow the same process as before. This is a modified version that logs the url and the response data, it would be interesting to see what's going on there.

[Map Generator.sketchplugin.zip](https://github.com/eddiesigner/sketch-map-generator/files/4124372/Map.Generator.sketchplugin.zip)

Just one last thing, can you please double check that your tokens don't have any empty spaces at the beginning or at the end?

**Comment by sli131** [comment]
It is working now :)

Embarrassed to say that your last tip revealed that the token was in fact entered twice, but wasn't visible since one token length fits exactly into the visible token field, hiding the double entry that followed in a 2nd line. 

Hard to imagine this was the culprit the whole time since I've pasted this code so many times in there... Also I am now using the plugin you posted above. Would you still like to see the console code generated?

Perhaps for "people like me" a larger token field would probably help :)

Thank so much for your help, really appreciated.

**Comment by eddiesigner** [comment]
I'm happy to know that you found the issue :)

I don't need to see the console log anymore, I will try to display a more useful error message and improve the UI in the future ;)
