### ISSUE TITLE
ios Catalina 

### ISSUE THREAD

**Issue by olczyna** [eddiesigner/sketch-map-generator#53]
Hi there, 

I just downloaded your plugin but looks like its not working on this operation system. Looks like it is not pulling the location when I want to generate the map.

Thanks, 
Aleks

**Comment by eddiesigner** [comment]
Hi,

Are you using Google Maps or Mapbox? In both cases please make sure of generating your own API keys:

https://github.com/eddiesigner/sketch-map-generator/wiki/How-to-generate-a-Google-Maps-key
https://github.com/eddiesigner/sketch-map-generator/wiki/How-to-get-your-Mapbox-tokens

The plugin works just fine with Mac OS Catalina.

Cheers.

**Comment by eddiesigner** [comment]
I will close this for now, please feel free to reopen it if needed.
