### ISSUE TITLE
Mapbox doesn't work with Sketch 52.6

### ISSUE THREAD

**Issue by ItsMeRiley** [eddiesigner/sketch-map-generator#55]
Hello,

I filled in my token/secret token from Mapbox but the text field where you input the address doesn't work, It doesn't allow me to type it only allows me to paste. If I drop in an address and I have tried a few to make sure the fault wasn't just a wrong address it will not generate a preview. If I click generate it will pop-up a small message at the bottom saying 'undefined'.
<img width="806" alt="Screen Shot 2020-04-12 at 12 32 41 PM" src="https://user-images.githubusercontent.com/29689874/79066887-7ad92080-7cbb-11ea-8ab9-38639a4afe1f.png">
<img width="1280" alt="Screen Shot 2020-04-12 at 12 38 17 PM" src="https://user-images.githubusercontent.com/29689874/79066889-7dd41100-7cbb-11ea-9b81-c934c49d146c.png">
<img width="176" alt="Screen Shot 2020-04-12 at 12 45 14 PM" src="https://user-images.githubusercontent.com/29689874/79066890-7f053e00-7cbb-11ea-85e5-1893b8e6b5b3.png">

**Comment by eddiesigner** [comment]
Hey,

what Sketch version are you using? also what macOS version do you have? I'm asking that because the UI looks weird, I guess it has do to something with that.

**Comment by ItsMeRiley** [comment]
Hey,

I am using Sketch 52.6 on Catalina 10.15.4

**Comment by eddiesigner** [comment]
I just realized that there is an issue with the UI framework that I used to build this plugin, most of the components don't work as expected with Sketch 52 and macOS Catalina, although it works well with Sketch 57+.

It would be possible for you to upgrade to Sketch 57? Or to use a Mac with Mojave?

If not, I built a modified version that works in Sketch 52.6, it's not perfect but it gets the job done. I added a button to close the window and the settings are saved automatically so you don't have to use the button to do so. Just be aware that the preview feature doesn't work in this version.

Download modified version:

[Map Generator.sketchplugin.zip](https://github.com/eddiesigner/sketch-map-generator/files/4477205/Map.Generator.sketchplugin.zip) (Unzip and double click `Map Generator.sketchplugin`)

I guess I should rewrite the entire plugin so it can use modern technologies but that would take some time, in the meantime you can use this modified version if you prefer.

**Comment by ItsMeRiley** [comment]
Thank you as far as I can tell that worked, if I experience any other problems I will just renew my Sketch license and update. Again thank you for the help!

_Small tip for people having issues with their Mapbox Styles not showing up in the dropdown, make sure your username is lowercase in the plugin settings. If you use caps anywhere it will not recognize your account and your styles will not appear._
