### ISSUE TITLE
[Feedback] Google Map Configuration Update (2020 June)

### ISSUE THREAD

**Issue by adong** [eddiesigner/sketch-map-generator#57]
Google no longer offers Step 2 in https://github.com/eddiesigner/sketch-map-generator/wiki/How-to-generate-a-Google-Maps-key

So you have to be selective, after trying out few combinations, I found out that once configured as following. 

```
Geocoding API 
Maps Static API
```

![image](https://user-images.githubusercontent.com/15989893/84582731-ab653580-ada4-11ea-85be-caf6517cf876.png)

You should be able to use google map preview & generate features. I found out that Geocoding API is essential to enable preview feature.

PS: of course, you can select all Maps & Places APIs for the sake of it.

**Comment by AlijahSmith** [comment]
The following was required for me.

- Geocoding API
- Maps JavaScript API
- Maps Static API

![Screen Shot 2020-06-16 at 10 59 54 AM](https://user-images.githubusercontent.com/2087826/84805035-dcba4d00-afc0-11ea-964d-36a429dbc865.png)

**Comment by eddiesigner** [comment]
Thank you both for your valuable feedback! 🙏 

I already updated [the documentation](https://github.com/eddiesigner/sketch-map-generator/wiki/How-to-generate-a-Google-Maps-key) with the new steps and more detailed information.
