### ISSUE TITLE
[Feature Request] Please Provide Official Support for Sketchpacks Instal & Auto-Update

### ISSUE THREAD

**Issue by luxlogica** [eddiesigner/sketch-map-generator#7]
Please provide official support for [Sketchpacks](https://sketchpacks.com/) - this is a project that deserves it. It allows the Sketch plugin developer to keep all their users automatically updated, with no work from their part - updates are delivered automatically from your GitHub repo, when you push to your 'master' branch.

Please have a look their [integrations page](https://github.com/integration/sketchpacks-relay), so we can get not just automatic version numbering, but also **auto-updating**!

**Comment by eddiesigner** [comment]
I didn't know anything about this application but I think it's really handy!

Thanks for the tip, the integration is ready! 👍
