### ISSUE TITLE
Feature Request: Ability to save Snazzy Maps Styles for Easy Reuse

### ISSUE THREAD

**Issue by aalokt89** [eddiesigner/sketch-map-generator#8]
I am working on an project in which map views are a  core part of the app. It's quite cumbersome to re-copy and paste the same style over and over again.

It would be amazing if there was a way to save a Snazzy Map style as a preset so I can easily create multiple maps and pick the style lightning fast.

**Comment by eddiesigner** [comment]
I think it's posible but I'm not sure about the user experience implementation because it could be a combo box where you can select previous styles or maybe it could be a checkbox where you can remember the last style. 

In the meantime you could use a shared style 😄

**Comment by aalokt89** [comment]
Yea, for sure. Not looking for anything crazy fancy. I think a 'remember last style' could be a great first solution.

**Comment by eddiesigner** [comment]
Sorry for the late but now you can remember the Snazzy styles and the other settings too 😎
