### ISSUE TITLE
Feature request: Remember address and zoom setting

### ISSUE THREAD

**Issue by denbue** [eddiesigner/sketch-map-generator#9]
It would be fantastic, if the plugin would remember the previously entered address and zoom-level. The snazzy maps style option is great, but entering all information when trying out styles is becoming very time-consuming.

Great plugin!

**Comment by eddiesigner** [comment]
Sorry for the late but now you can remember all the settings 😎

**Comment by denbue** [comment]
Thanks a lot for implementing the feature!
